<a href="https://colab.research.google.com/github/jorgegarcia396/hacking-civico/blob/master/03_exploracion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Para descargar el conjunto de datos
!wget http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip

# Para descargar el diccionario de los datos
!wget http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip

# Descomprimimos ambas carpetas y movemos archivos
!unzip datos_abiertos_covid19.zip
!unzip diccionario_datos_covid19.zip
!mv ./diccionario_datos_covid19/*.xlsx .
!mv *COVID19MEXICO.csv COVID19MEXICO.csv

# Eliminamos las carpetas comprimidas
!rm -rf diccionario_datos_covid19
!rm datos_abiertos_covid19.zip
!rm diccionario_datos_covid19.zip

--2020-09-13 15:06:06--  http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip
Resolving datosabiertos.salud.gob.mx (datosabiertos.salud.gob.mx)... 187.210.186.146
Connecting to datosabiertos.salud.gob.mx (datosabiertos.salud.gob.mx)|187.210.186.146|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31945189 (30M) [application/x-zip-compressed]
Saving to: ‘datos_abiertos_covid19.zip’

datos_abiertos_covi 100%[===================>]  30.46M  19.2MB/s    in 1.6s

2020-09-13 15:06:08 (19.2 MB/s) - ‘datos_abiertos_covid19.zip’ saved [31945189/31945189]

--2020-09-13 15:06:08--  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Resolving epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)... 187.191.75.207
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip [following]
--2020-09-13 15:06:08--  https://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 81416 (80K) [application/x-zip-compressed]
Saving to: ‘diccionario_datos_covid19.zip’

diccionario_datos_c 100%[===================>]  79.51K  --.-KB/s    in 0.06s

2020-09-13 15:06:09 (1.27 MB/s) - ‘diccionario_datos_covid19.zip’ saved [81416/81416]

Archive:  datos_abiertos_covid19.zip
  inflating: 200912COVID19MEXICO.csv
Archive:  diccionario_datos_covid19.zip
  inflating: diccionario_datos_covid19/Catalogos_0412.xlsx
  inflating: diccionario_datos_covid19/Descriptores_0419.xlsx

In [ ]:
import statistics

import pandas as pd
import numpy as np

nombre_archivo = 'COVID19MEXICO.csv'
data = pd.read_csv(nombre_archivo, encoding='latin-1')
data.head()

  FECHA_ACTUALIZACION ID_REGISTRO  ORIGEN  ...  PAIS_NACIONALIDAD  PAIS_ORIGEN  UCI
0          2020-09-12      114cd3       2  ...            MÃ©xico           99   97
1          2020-09-12      0bafd8       2  ...            MÃ©xico           99    2
2          2020-09-12      18747a       2  ...            MÃ©xico           99   97
3          2020-09-12      174174       2  ...            MÃ©xico           99   97
4          2020-09-12      0eae86       2  ...            MÃ©xico           99    1

[5 rows x 35 columns]

In [ ]:
nombre_diccionario = 'Descriptores_0419.xlsx'
diccionario = pd.read_excel(nombre_diccionario)
diccionario

    Nº  ...                                   FORMATO O FUENTE
0    1  ...                                         AAAA-MM-DD
1    2  ...                                             TEXTO
2    3  ...  CATÁLOGO: ORIGEN                              ...
3    4  ...  CATÁLOGO: SECTOR                              ...
4    5  ...                                CATALÓGO: ENTIDADES
5    6  ...       CATÁLOGO: SEXO
6    7  ...                                CATALÓGO: ENTIDADES
7    8  ...                                CATALÓGO: ENTIDADES
8    9  ...                               CATALÓGO: MUNICIPIOS
9   10  ...                           CATÁLOGO: TIPO_PACIENTE
10  11  ...                                         AAAA-MM-DD
11  12  ...                                         AAAA-MM-DD
12  13  ...                                         AAAA-MM-DD
13  14  ...  CATÁLOGO: SI_ NO                              ...
14  15  ...  CATÁLOGO: SI_ NO                              ...
15  16  ...                                   NÚMERICA EN AÑOS
16  17  ...                            CATÁLOGO: NACIONALIDAD
17  18  ...  CATÁLOGO: SI_ NO                              ...
18  19  ...  CATÁLOGO: SI_ NO                              ...
19  20  ...  CATÁLOGO: SI_ NO                              ...
20  21  ...  CATÁLOGO: SI_ NO                              ...
21  22  ...  CATÁLOGO: SI_ NO                              ...
22  23  ...  CATÁLOGO: SI_ NO                              ...
23  24  ...  CATÁLOGO: SI_ NO                              ...
24  25  ...  CATÁLOGO: SI_ NO                              ...
25  26  ...  CATÁLOGO: SI_ NO                              ...
26  27  ...  CATÁLOGO: SI_ NO                              ...
27  28  ...  CATÁLOGO: SI_ NO                              ...
28  29  ...  CATÁLOGO: SI_ NO                              ...
29  30  ...  CATÁLOGO: SI_ NO                              ...
30  31  ...                                CATÁLOGO: RESULTADO
31  32  ...  CATÁLOGO: SI_ NO                              ...
32  33  ...                               TEXTO, 99= SE IGNORA
33  34  ...                               TEXTO, 97= NO APLICA
34  35  ...  CATÁLOGO: SI_ NO                              ...

[35 rows x 4 columns]

In [ ]:

nombre_cat = 'Catalogos_0412.xlsx'
sheets = ['ORIGEN', 'SECTOR', 'SEXO', 'TIPO_PACIENTE', 'SI_NO', 'NACIONALIDAD', 'RESULTADO', 'de ENTIDADES', 'MUNICIPIOS']
catalogues = {}
for sheet in sheets:
  catalogue = pd.read_excel(nombre_cat, sheet_name='Catálogo ' + sheet)
  catalogue.columns = catalogue.columns.str.replace(' ', '_')
  catalogue.columns = catalogue.columns.str.replace('.', '')
  catalogue.columns = catalogue.columns.str.lower()
  new_catalogue = {sheet: catalogue}
  catalogues.update(new_catalogue)

In [ ]:
catalogues

{'MUNICIPIOS':       clave_municipio        municipio  clave_entidad
 0                   1   AGUASCALIENTES              1
 1                   2         ASIENTOS              1
 2                   3         CALVILLO              1
 3                   4            COSÍO              1
 4                   5      JESÚS MARÍA              1
 ...               ...              ...            ...
 2496              999  NO ESPECIFICADO             32
 2497              999  NO ESPECIFICADO             36
 2498              997        NO APLICA             97
 2499              998        SE IGNORA             98
 2500              999  NO ESPECIFICADO             99

 [2501 rows x 3 columns], 'NACIONALIDAD':    clave      descripción
 0      1         MEXICANA
 1      2       EXTRANJERA
 2     99  NO ESPECIFICADO, 'ORIGEN':    clave      descripción
 0      1            USMER
 1      2   FUERA DE USMER
 2     99  NO ESPECIFICADO, 'RESULTADO':   unnamed:_0              unnamed:_1
 0      CLAVE             DESCRIPCIÓN
 1          1     Positivo SARS-CoV-2
 2          2  No positivo SARS-CoV-2
 3          3     Resultado pendiente, 'SECTOR':     clave      descripción
 0       1        CRUZ ROJA
 1       2              DIF
 2       3          ESTATAL
 3       4             IMSS
 4       5   IMSS-BIENESTAR
 5       6           ISSSTE
 6       7        MUNICIPAL
 7       8            PEMEX
 8       9          PRIVADA
 9      10           SEDENA
 10     11            SEMAR
 11     12              SSA
 12     13    UNIVERSITARIO
 13     99  NO ESPECIFICADO, 'SEXO':    clave      descripción
 0      1            MUJER
 1      2           HOMBRE
 2     99  NO ESPECIFICADO, 'SI_NO':    clave      descripción
 0      1              SI
 1      2              NO
 2     97        NO APLICA
 3     98        SE IGNORA
 4     99  NO ESPECIFICADO, 'TIPO_PACIENTE':    clave      descripción
 0      1      AMBULATORIO
 1      2    HOSPITALIZADO
 2     99  NO ESPECIFICADO, 'de ENTIDADES':     clave_entidad               entidad_federativa abreviatura
 0               1                   AGUASCALIENTES          AS
 1               2                  BAJA CALIFORNIA          BC
 2               3              BAJA CALIFORNIA SUR          BS
 3               4                         CAMPECHE          CC
 4               5             COAHUILA DE ZARAGOZA          CL
 5               6                           COLIMA          CM
 6               7                          CHIAPAS          CS
 7               8                        CHIHUAHUA          CH
 8               9                 CIUDAD DE MÉXICO          DF
 9              10                          DURANGO          DG
 10             11                       GUANAJUATO          GT
 11             12                         GUERRERO          GR
 12             13                          HIDALGO          HG
 13             14                          JALISCO          JC
 14             15                           MÉXICO          MC
 15             16              MICHOACÁN DE OCAMPO          MN
 16             17                          MORELOS          MS
 17             18                          NAYARIT          NT
 18             19                       NUEVO LEÓN          NL
 19             20                           OAXACA          OC
 20             21                           PUEBLA          PL
 21             22                        QUERÉTARO          QT
 22             23                     QUINTANA ROO          QR
 23             24                  SAN LUIS POTOSÍ          SP
 24             25                          SINALOA          SL
 25             26                           SONORA          SR
 26             27                          TABASCO          TC
 27             28                       TAMAULIPAS          TS
 28             29                         TLAXCALA          TL
 29             30  VERACRUZ DE IGNACIO DE LA LLAVE          VZ
 30             31                          YUCATÁN          YN
 31             32                        ZACATECAS          ZS
 32             36         ESTADOS UNIDOS MEXICANOS         EUM
 33             97                        NO APLICA         NaN
 34             98                        SE IGNORA          SI
 35             99                  NO ESPECIFICADO          NE}

In [ ]:
catalogues['SEXO']

   clave      descripción
0      1            MUJER
1      2           HOMBRE
2     99  NO ESPECIFICADO

In [ ]:
# dimensión de los datos
print('Número de filas: {}'.format(data.shape[0]))
print('Número de columnas: {}'.format(data.shape[1]))

Número de filas: 1510311
Número de columnas: 35

In [ ]:
# columnas (variables)
data.columns

Index(['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'DIABETES',
       'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'RESULTADO', 'MIGRANTE', 'PAIS_NACIONALIDAD',
       'PAIS_ORIGEN', 'UCI'],
      dtype='object')

In [ ]:
# limpieza del nombre de las columnas, remover espacios, carácteres especiales y pasar a minúsculas
data.columns = data.columns.str.replace(' ', '_')
data.columns = data.columns.str.replace('.', '')
data.columns = data.columns.str.lower()

In [ ]:
# calcular número de valores nulos por columna
for col in data.columns:
  print('Valores nulos en "{}": {}'.format(col,data[col].isna().sum()))

Valores nulos en "fecha_actualizacion": 0
Valores nulos en "id_registro": 0
Valores nulos en "origen": 0
Valores nulos en "sector": 0
Valores nulos en "entidad_um": 0
Valores nulos en "sexo": 0
Valores nulos en "entidad_nac": 0
Valores nulos en "entidad_res": 0
Valores nulos en "municipio_res": 0
Valores nulos en "tipo_paciente": 0
Valores nulos en "fecha_ingreso": 0
Valores nulos en "fecha_sintomas": 0
Valores nulos en "fecha_def": 0
Valores nulos en "intubado": 0
Valores nulos en "neumonia": 0
Valores nulos en "edad": 0
Valores nulos en "nacionalidad": 0
Valores nulos en "embarazo": 0
Valores nulos en "habla_lengua_indig": 0
Valores nulos en "diabetes": 0
Valores nulos en "epoc": 0
Valores nulos en "asma": 0
Valores nulos en "inmusupr": 0
Valores nulos en "hipertension": 0
Valores nulos en "otra_com": 0
Valores nulos en "cardiovascular": 0
Valores nulos en "obesidad": 0
Valores nulos en "renal_cronica": 0
Valores nulos en "tabaquismo": 0
Valores nulos en "otro_caso": 0
Valores nulos en "resultado": 0
Valores nulos en "migrante": 0
Valores nulos en "pais_nacionalidad": 0
Valores nulos en "pais_origen": 0
Valores nulos en "uci": 0

In [ ]:

# tipos de datos
data.dtypes

fecha_actualizacion    object
id_registro            object
origen                  int64
sector                  int64
entidad_um              int64
sexo                    int64
entidad_nac             int64
entidad_res             int64
municipio_res           int64
tipo_paciente           int64
fecha_ingreso          object
fecha_sintomas         object
fecha_def              object
intubado                int64
neumonia                int64
edad                    int64
nacionalidad            int64
embarazo                int64
habla_lengua_indig      int64
diabetes                int64
epoc                    int64
asma                    int64
inmusupr                int64
hipertension            int64
otra_com                int64
cardiovascular          int64
obesidad                int64
renal_cronica           int64
tabaquismo              int64
otro_caso               int64
resultado               int64
migrante                int64
pais_nacionalidad      object
pais_origen            object
uci                     int64
dtype: object

In [ ]:
# convertimos a fecha algunas columnas
def cast_datetime_cols(df):
    timestamp_cols = [col for col in df.columns if "fecha" in col]
    df[timestamp_cols] = df[timestamp_cols].apply(lambda date_col: pd.to_datetime(date_col, errors="coerce"), axis=0)
    return df

data = cast_datetime_cols(data)

In [ ]:
data.head()

  fecha_actualizacion id_registro  origen  ...  pais_nacionalidad  pais_origen  uci
0          2020-09-12      114cd3       2  ...            MÃ©xico           99   97
1          2020-09-12      0bafd8       2  ...            MÃ©xico           99    2
2          2020-09-12      18747a       2  ...            MÃ©xico           99   97
3          2020-09-12      174174       2  ...            MÃ©xico           99   97
4          2020-09-12      0eae86       2  ...            MÃ©xico           99    1

[5 rows x 35 columns]

In [ ]:
# unimos los datos con los catalogos para tener mejor entendimiento de ellos
data = (
    # unimos con el catálogo MUNICIPIOS y ENTIDADES
    data.merge(catalogues['de ENTIDADES'], how='left', left_on='entidad_res', right_on='clave_entidad').
    drop(columns=['entidad_res', 'abreviatura']).
    rename(columns={'entidad_federativa':'entidad_res'}).
    merge(catalogues['MUNICIPIOS'], how='left', left_on=['clave_entidad','municipio_res'], right_on=['clave_entidad','clave_municipio']).
    drop(columns=['municipio_res', 'clave_entidad', 'clave_municipio']).
    rename(columns={'municipio':'municipio_res'})
)

In [ ]:
# unimos con el catálogo de ENTIDADES
entidades_cols = [col for col in data.columns if "entidad" in col and col != 'entidad_res']
for col in entidades_cols:
    data = (
        data.merge(catalogues['de ENTIDADES'], how='left', left_on=col, right_on='clave_entidad').
        drop(columns=[col, 'abreviatura', 'clave_entidad']).
        rename(columns={'entidad_federativa':col})
    )

In [ ]:
# unimos con el catálogo SI_NO
sino_cols = ['intubado', 'neumonia', 'embarazo', 'habla_lengua_indig', 'diabetes', 'epoc', 'asma', 'inmusupr',
             'hipertension', 'otra_com', 'cardiovascular', 'obesidad', 'renal_cronica', 'tabaquismo', 
             'otro_caso', 'migrante', 'uci']
for col in sino_cols:
    data = (
        data.merge(catalogues['SI_NO'], how='left', left_on=col, right_on='clave').
        drop(columns=[col, 'clave']).
        rename(columns={'descripción':col})
    )

In [ ]:
catalogues['RESULTADO'].columns

Index(['unnamed:_0', 'unnamed:_1'], dtype='object')

In [ ]:
catalogues['RESULTADO'].columns = ['clave', 'descripción']
catalogues['RESULTADO'].columns

Index(['clave', 'descripción'], dtype='object')

In [ ]:
catalogues['RESULTADO'] = catalogues['RESULTADO'].drop(index=0)

In [ ]:
catalogues['RESULTADO']['clave'] = catalogues['RESULTADO']['clave'].astype(int)

In [ ]:
# unimos otras columnnas que comparten lógica
other_cols = ['origen', 'sector', 'sexo', 'tipo_paciente', 'nacionalidad', 'resultado']
for col, cat in zip(other_cols, [x.upper() for x in other_cols]):
    data = (
        data.merge(catalogues[cat], how='left', left_on=col, right_on='clave').
        drop(columns=[col, 'clave']).
        rename(columns={'descripción':col})
    )

In [ ]:
# creamos algunas variables que podrían ser útiles después
data['defuncion'] = ~data.fecha_def.isna()
data['mes_def'] = data.fecha_def.dt.month
data['año_def'] = data.fecha_def.dt.year
data['mes_ingreso'] = data.fecha_ingreso.dt.month
data['año_ingreso'] = data.fecha_ingreso.dt.year

In [ ]:
data.head()

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
0          2020-09-12      114cd3  ...           7        2020
1          2020-09-12      0bafd8  ...           4        2020
2          2020-09-12      18747a  ...           4        2020
3          2020-09-12      174174  ...           4        2020
4          2020-09-12      0eae86  ...           4        2020

[5 rows x 40 columns]

In [ ]:
# usando query
data.query('nacionalidad == "MEXICANA"').head(2)

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
0          2020-09-12      114cd3  ...           7        2020
1          2020-09-12      0bafd8  ...           4        2020

[2 rows x 40 columns]

In [ ]:
# haciendo referencia a la columna como índice
data[data['nacionalidad'] == 'MEXICANA'].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
0          2020-09-12      114cd3  ...           7        2020
1          2020-09-12      0bafd8  ...           4        2020

[2 rows x 40 columns]

In [ ]:
# seleccionando directamente la columna que queremos filtrar
data[data.nacionalidad == 'MEXICANA'].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
0          2020-09-12      114cd3  ...           7        2020
1          2020-09-12      0bafd8  ...           4        2020

[2 rows x 40 columns]

In [ ]:
# usando query podemos poner en el string del query todas las condiciones que queramos
data.query('nacionalidad == "MEXICANA" & entidad_res == "CIUDAD DE MÉXICO"').head(2)

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
3          2020-09-12      174174  ...           4        2020
6          2020-09-12      1a73c1  ...           5        2020

[2 rows x 40 columns]

In [ ]:
# usando el filtrado tradicional debemos encerrar en paréntesis cada condición que queremos que cumpla nuestro filtro
data[(data['nacionalidad'] == "MEXICANA") & (data.entidad_res == "CIUDAD DE MÉXICO")].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
3          2020-09-12      174174  ...           4        2020
6          2020-09-12      1a73c1  ...           5        2020

[2 rows x 40 columns]

In [ ]:
# una columna, una métrica
data.groupby('sexo').edad.mean()

sexo
HOMBRE    42.667259
MUJER     41.639353
Name: edad, dtype: float64

In [ ]:
# una columna, varias métricas
data.groupby('sexo').agg({'edad': ['min','mean','max']})

       edad
        min       mean  max
sexo
HOMBRE    0  42.667259  120
MUJER     0  41.639353  120

In [ ]:
# varias columnas, una métrica
data.groupby('sexo').agg({'edad': 'mean', 'mes_ingreso': 'mean', 'mes_def': 'mean'})

             edad  mes_ingreso   mes_def
sexo
HOMBRE  42.667259     6.730779  6.497591
MUJER   41.639353     6.807770  6.572409

In [ ]:
# varias columnas, varias métricas
data.groupby('sexo').agg({'edad': ['min','mean','max'], 'mes_ingreso': ['min','mean','max'], 'mes_def': ['min','mean','max']})

       edad                 mes_ingreso               mes_def
        min       mean  max         min      mean max     min      mean  max
sexo
HOMBRE    0  42.667259  120           1  6.730779   9     1.0  6.497591  9.0
MUJER     0  41.639353  120           1  6.807770   9     1.0  6.572409  9.0

In [ ]:
# Filtrar por tipos generales (categóricas y numéricas)
numerical = data.select_dtypes(include='number')
categorical = data.select_dtypes(include=['object', 'bool', 'category', 'datetime64[ns]'])

In [ ]:
numerical.head()

   edad  mes_def  año_def  mes_ingreso  año_ingreso
0    52      NaN      NaN            7         2020
1    57      5.0   2020.0            4         2020
2    44      NaN      NaN            4         2020
3    28      NaN      NaN            4         2020
4    53      NaN      NaN            4         2020

In [ ]:
categorical.head()

  fecha_actualizacion id_registro  ...            resultado defuncion
0          2020-09-12      114cd3  ...  Positivo SARS-CoV-2     False
1          2020-09-12      0bafd8  ...  Positivo SARS-CoV-2      True
2          2020-09-12      18747a  ...  Positivo SARS-CoV-2     False
3          2020-09-12      174174  ...  Positivo SARS-CoV-2     False
4          2020-09-12      0eae86  ...  Positivo SARS-CoV-2     False

[5 rows x 35 columns]

In [ ]:
# para conocer todos los tipo de datos
?data.select_dtypes

In [ ]:
# Cardinalidad - Valores únicos por columna
for col in categorical.columns:
  print('Valores únicos en "{}": {}'.format(col,categorical[col].nunique()))

Valores únicos en "fecha_actualizacion": 1
Valores únicos en "id_registro": 1510311
Valores únicos en "fecha_ingreso": 256
Valores únicos en "fecha_sintomas": 256
Valores únicos en "fecha_def": 201
Valores únicos en "pais_nacionalidad": 119
Valores únicos en "pais_origen": 77
Valores únicos en "entidad_res": 32
Valores únicos en "municipio_res": 2164
Valores únicos en "entidad_um": 32
Valores únicos en "entidad_nac": 33
Valores únicos en "intubado": 4
Valores únicos en "neumonia": 3
Valores únicos en "embarazo": 4
Valores únicos en "habla_lengua_indig": 3
Valores únicos en "diabetes": 3
Valores únicos en "epoc": 3
Valores únicos en "asma": 3
Valores únicos en "inmusupr": 3
Valores únicos en "hipertension": 3
Valores únicos en "otra_com": 3
Valores únicos en "cardiovascular": 3
Valores únicos en "obesidad": 3
Valores únicos en "renal_cronica": 3
Valores únicos en "tabaquismo": 3
Valores únicos en "otro_caso": 3
Valores únicos en "migrante": 3
Valores únicos en "uci": 4
Valores únicos en "origen": 2
Valores únicos en "sector": 14
Valores únicos en "sexo": 2
Valores únicos en "tipo_paciente": 2
Valores únicos en "nacionalidad": 2
Valores únicos en "resultado": 3
Valores únicos en "defuncion": 2

In [ ]:
# Unicidad - proporción de valores únicos por columna
total = data.shape[0]
for col in categorical.columns:
  print('Porcentaje de valores únicos en "{}": {}%'.format(col,round(categorical[col].nunique()/total*100,2)))

Porcentaje de valores únicos en "fecha_actualizacion": 0.0%
Porcentaje de valores únicos en "id_registro": 100.0%
Porcentaje de valores únicos en "fecha_ingreso": 0.02%
Porcentaje de valores únicos en "fecha_sintomas": 0.02%
Porcentaje de valores únicos en "fecha_def": 0.01%
Porcentaje de valores únicos en "pais_nacionalidad": 0.01%
Porcentaje de valores únicos en "pais_origen": 0.01%
Porcentaje de valores únicos en "entidad_res": 0.0%
Porcentaje de valores únicos en "municipio_res": 0.14%
Porcentaje de valores únicos en "entidad_um": 0.0%
Porcentaje de valores únicos en "entidad_nac": 0.0%
Porcentaje de valores únicos en "intubado": 0.0%
Porcentaje de valores únicos en "neumonia": 0.0%
Porcentaje de valores únicos en "embarazo": 0.0%
Porcentaje de valores únicos en "habla_lengua_indig": 0.0%
Porcentaje de valores únicos en "diabetes": 0.0%
Porcentaje de valores únicos en "epoc": 0.0%
Porcentaje de valores únicos en "asma": 0.0%
Porcentaje de valores únicos en "inmusupr": 0.0%
Porcentaje de valores únicos en "hipertension": 0.0%
Porcentaje de valores únicos en "otra_com": 0.0%
Porcentaje de valores únicos en "cardiovascular": 0.0%
Porcentaje de valores únicos en "obesidad": 0.0%
Porcentaje de valores únicos en "renal_cronica": 0.0%
Porcentaje de valores únicos en "tabaquismo": 0.0%
Porcentaje de valores únicos en "otro_caso": 0.0%
Porcentaje de valores únicos en "migrante": 0.0%
Porcentaje de valores únicos en "uci": 0.0%
Porcentaje de valores únicos en "origen": 0.0%
Porcentaje de valores únicos en "sector": 0.0%
Porcentaje de valores únicos en "sexo": 0.0%
Porcentaje de valores únicos en "tipo_paciente": 0.0%
Porcentaje de valores únicos en "nacionalidad": 0.0%
Porcentaje de valores únicos en "resultado": 0.0%
Porcentaje de valores únicos en "defuncion": 0.0%

In [ ]:
# Moda - valor que más se repite en cada columna excepto los indicadores únicos
for col in categorical.drop(columns='id_registro').columns:
  print('Valor más popular en "{}": {}'.format(col, statistics.mode(categorical[col])))

Valor más popular en "fecha_actualizacion": 2020-09-12 00:00:00
Valor más popular en "fecha_ingreso": 2020-07-20 00:00:00
Valor más popular en "fecha_sintomas": 2020-07-20 00:00:00
Valor más popular en "fecha_def": NaT
Valor más popular en "pais_nacionalidad": MÃ©xico
Valor más popular en "pais_origen": 99
Valor más popular en "entidad_res": CIUDAD DE MÉXICO
Valor más popular en "municipio_res": IZTAPALAPA
Valor más popular en "entidad_um": CIUDAD DE MÉXICO
Valor más popular en "entidad_nac": CIUDAD DE MÉXICO
Valor más popular en "intubado": NO APLICA
Valor más popular en "neumonia": NO
Valor más popular en "embarazo": NO
Valor más popular en "habla_lengua_indig": NO
Valor más popular en "diabetes": NO
Valor más popular en "epoc": NO
Valor más popular en "asma": NO
Valor más popular en "inmusupr": NO
Valor más popular en "hipertension": NO
Valor más popular en "otra_com": NO
Valor más popular en "cardiovascular": NO
Valor más popular en "obesidad": NO
Valor más popular en "renal_cronica": NO
Valor más popular en "tabaquismo": NO
Valor más popular en "otro_caso": SI
Valor más popular en "migrante": NO ESPECIFICADO
Valor más popular en "uci": NO APLICA
Valor más popular en "origen": FUERA DE USMER
Valor más popular en "sector": SSA
Valor más popular en "sexo": MUJER
Valor más popular en "tipo_paciente": AMBULATORIO
Valor más popular en "nacionalidad": MEXICANA
Valor más popular en "resultado": No positivo SARS-CoV-2
Valor más popular en "defuncion": False

In [ ]:
numerical.describe()

               edad       mes_def  año_def   mes_ingreso  año_ingreso
count  1.510311e+06  90195.000000  90195.0  1.510311e+06    1510311.0
mean   4.214413e+01      6.524896   2020.0  6.769961e+00       2020.0
std    1.680812e+01      1.306444      0.0  1.395983e+00          0.0
min    0.000000e+00      1.000000   2020.0  1.000000e+00       2020.0
25%    3.000000e+01      6.000000   2020.0  6.000000e+00       2020.0
50%    4.100000e+01      7.000000   2020.0  7.000000e+00       2020.0
75%    5.300000e+01      8.000000   2020.0  8.000000e+00       2020.0
max    1.200000e+02      9.000000   2020.0  9.000000e+00       2020.0

In [ ]:
# ¿Cuántas pruebas por origen se realizan?
data.groupby('origen').id_registro.count()

origen
FUERA DE USMER    1010999
USMER              499312
Name: id_registro, dtype: int64

In [ ]:
data.origen.value_counts()

FUERA DE USMER    1010999
USMER              499312
Name: origen, dtype: int64

In [ ]:
# ¿Cuántas pruebas por sector se realizan?
data.sector.value_counts()

SSA                942672
IMSS               386225
ISSSTE              57072
PRIVADA             55614
ESTATAL             27163
PEMEX               12919
IMSS-BIENESTAR      10158
SEMAR                7796
SEDENA               7371
MUNICIPAL            1201
UNIVERSITARIO        1046
DIF                   843
CRUZ ROJA             223
NO ESPECIFICADO         8
Name: sector, dtype: int64

In [ ]:
# ¿Cuántos pacientes por sexo tenemos?
data.sexo.value_counts()

MUJER     768635
HOMBRE    741676
Name: sexo, dtype: int64

In [ ]:
# ¿Cuál es la proporción de los pacientes por sexo?
data.sexo.value_counts(normalize=True)

MUJER     0.508925
HOMBRE    0.491075
Name: sexo, dtype: float64

In [ ]:
# ¿Cuál es la proporción de resultados de las pruebas?
data.resultado.value_counts(normalize=True)

No positivo SARS-CoV-2    0.502670
Positivo SARS-CoV-2       0.439627
Resultado pendiente       0.057703
Name: resultado, dtype: float64

In [ ]:
# ¿Cuántas pruebas positivas tenemos en el set?
data[data.resultado == 'Positivo SARS-CoV-2'].id_registro.count()

663973

In [ ]:
# ¿Cuántos casos positivos tenemos por mes?
data[data.resultado == 'Positivo SARS-CoV-2'].mes_ingreso.value_counts().sort_index()

1         2
2         8
3      2530
4     26567
5     86557
6    152980
7    199471
8    155971
9     39887
Name: mes_ingreso, dtype: int64

In [ ]:
# ¿Cuál es el resultado de las pruebas por sexo?
data.groupby(['sexo','resultado'])['id_registro'].count()

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    352619
        Positivo SARS-CoV-2       346464
        Resultado pendiente        42593
MUJER   No positivo SARS-CoV-2    406569
        Positivo SARS-CoV-2       317509
        Resultado pendiente        44557
Name: id_registro, dtype: int64

In [ ]:
data.groupby('sexo').resultado.value_counts()

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    352619
        Positivo SARS-CoV-2       346464
        Resultado pendiente        42593
MUJER   No positivo SARS-CoV-2    406569
        Positivo SARS-CoV-2       317509
        Resultado pendiente        44557
Name: resultado, dtype: int64

In [ ]:
# ¿Qué proporción de resultados de pruebas tenemos por sexo?
data.groupby('sexo').resultado.value_counts(normalize=True)

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    0.475435
        Positivo SARS-CoV-2       0.467137
        Resultado pendiente       0.057428
MUJER   No positivo SARS-CoV-2    0.528949
        Positivo SARS-CoV-2       0.413082
        Resultado pendiente       0.057969
Name: resultado, dtype: float64

In [ ]:
# ¿Cuál es la edad de los pacientes por sexo?
data.groupby('sexo').edad.describe()

           count       mean        std  min   25%   50%   75%    max
sexo
HOMBRE  741676.0  42.667259  17.126286  0.0  30.0  41.0  54.0  120.0
MUJER   768635.0  41.639353  16.479581  0.0  30.0  40.0  52.0  120.0

In [ ]:
def q25(x):
  return x.quantile(0.25)

def q75(x):
  return x.quantile(0.75)

data.groupby('sexo').agg({'edad': ['min', q25, 'median', q75, 'max']})

       edad
        min q25 median q75  max
sexo
HOMBRE    0  30     41  54  120
MUJER     0  30     40  52  120

In [ ]:
# ¿Cuál es la edad de los pacientes dependiendo de si son intubados o no?
data.groupby('intubado').edad.describe()

                     count       mean        std  min   25%   50%   75%    max
intubado
NO                221572.0  53.304786  19.684371  0.0  42.0  55.0  67.0  118.0
NO APLICA        1248894.0  39.686951  15.079782  0.0  29.0  38.0  49.0  120.0
NO ESPECIFICADO      194.0  54.443299  16.817502  0.0  45.0  57.0  65.0   92.0
SI                 39651.0  57.111826  17.914277  0.0  48.0  59.0  69.0  108.0

In [ ]:
data.groupby('intubado').agg({'edad': ['min', q25, 'median', q75, 'max']})

                edad
                 min q25 median q75  max
intubado
NO                 0  42     55  67  118
NO APLICA          0  29     38  49  120
NO ESPECIFICADO    0  45     57  65   92
SI                 0  48     59  69  108

In [ ]:
# ¿Cuál es la edad máxima y cuál es la mínima de los pacientes fallecidos?
edad_def_max = data[data.defuncion].edad.max()
data[data.defuncion & (data.edad == edad_def_max)]

       fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
581442          2020-09-12      1b7b20  ...           5        2020

[1 rows x 40 columns]

In [ ]:
edad_def_min = data[data.defuncion].edad.min()
data[data.defuncion & (data.edad == edad_def_min)]

        fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
11277            2020-09-12      18feee  ...           6        2020
11565            2020-09-12      083c34  ...           5        2020
26116            2020-09-12      02f8e2  ...           5        2020
50494            2020-09-12      014b5d  ...           5        2020
60925            2020-09-12      053398  ...           6        2020
...                     ...         ...  ...         ...         ...
1439056          2020-09-12      0860f4  ...           6        2020
1462455          2020-09-12      1e94e4  ...           8        2020
1473848          2020-09-12      00f39c  ...           7        2020
1487374          2020-09-12      07cf0b  ...           8        2020
1502388          2020-09-12      3b8095  ...           9        2020

[252 rows x 40 columns]

In [ ]:
# ¿Cuál es la edad de los pacientes que fallecen?
data.groupby('defuncion').edad.describe()

               count       mean        std  min   25%   50%   75%    max
defuncion
False      1420116.0  40.888838  16.104672  0.0  29.0  39.0  51.0  120.0
True         90195.0  61.908676  15.218544  0.0  53.0  63.0  73.0  109.0

In [ ]:
# ¿Cuántas defunciones tenemos por mes?
data[data.defuncion].mes_def.value_counts().sort_index()

1.0        6
2.0       12
3.0      232
4.0     5294
5.0    16091
6.0    21461
7.0    23855
8.0    18791
9.0     4453
Name: mes_def, dtype: int64

In [ ]:
# ¿Cuál es la proporción de diábeticos para las defunciones?
data.groupby('diabetes').defuncion.value_counts(normalize=True)

diabetes   defuncion
NO         False        0.958145
           True         0.041855
SE IGNORA  False        0.873868
           True         0.126132
SI         False        0.813339
           True         0.186661
Name: defuncion, dtype: float64

In [ ]:
# ¿Cuál es la proporción de asmáticos para las defunciones?
data.groupby('asma').defuncion.value_counts(normalize=True)

asma       defuncion
NO         False        0.939952
           True         0.060048
SE IGNORA  False        0.867149
           True         0.132851
SI         False        0.958165
           True         0.041835
Name: defuncion, dtype: float64

In [ ]:
#¿Tienen los pacientes con hipertensión un riesgo más alto de defunción?
data.groupby('hipertension').defuncion.value_counts(normalize=True)

hipertension  defuncion
NO            False        0.960768
              True         0.039232
SE IGNORA     False        0.873276
              True         0.126724
SI            False        0.834452
              True         0.165548
Name: defuncion, dtype: float64

In [ ]:
 # ¿Cuántos casos confirmados se tienen por Estado?
 #data.groupby('entidad_res').resultado.value_counts(normalize=True)
 data.groupby('entidad_res').resultado.value_counts()

entidad_res      resultado
AGUASCALIENTES   No positivo SARS-CoV-2    12676
                 Positivo SARS-CoV-2        6331
                 Resultado pendiente         711
BAJA CALIFORNIA  Positivo SARS-CoV-2       18299
                 No positivo SARS-CoV-2    10654
                                           ...
YUCATÁN          No positivo SARS-CoV-2    14407
                 Resultado pendiente         739
ZACATECAS        No positivo SARS-CoV-2     7371
                 Positivo SARS-CoV-2        6290
                 Resultado pendiente         169
Name: resultado, Length: 96, dtype: int64

In [ ]:
# ¿Cuántas defunciones se tienen por Estado?
data.groupby('entidad_res').defuncion.value_counts(normalize=True)

entidad_res                      defuncion
AGUASCALIENTES                   False        0.969571
                                 True         0.030429
BAJA CALIFORNIA                  False        0.863585
                                 True         0.136415
BAJA CALIFORNIA SUR              False        0.973138
                                                ...
VERACRUZ DE IGNACIO DE LA LLAVE  True         0.099027
YUCATÁN                          False        0.942372
                                 True         0.057628
ZACATECAS                        False        0.943890
                                 True         0.056110
Name: defuncion, Length: 64, dtype: float64

In [ ]:
data[data.defuncion & (data.entidad_res == "CIUDAD DE MÉXICO")].defuncion.value_counts()

True    12012
Name: defuncion, dtype: int64